config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account', controllers: { registrations: :registrations } }  do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  match '/admin',                      to: 'admin#admin_website',                   as: :admin_website
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',                to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  match '/admin/bank-setup',                   to: 'admin#admin_bank_setup',                as: :admin_bank_setup
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home


  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/views/admin/_footer.html.erb
<div id="admin-footer">
  <div class="container clearfix">
    <p class="pull-right">© 2013 Crowdhoster.com</p>
  </div>
</div>

app/views/admin/_header.html.erb
<h3>
  Admin > <%= link_to @settings.site_name, root_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  <span class="loader" data-loader="admin_header" style="display:none"></span>
</h3>

<ul class="nav nav-pills">
  <li class="<%= 'active' if active == 'website' %>">
    <%= link_to "Website", admin_website_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="<%= 'active' if active == 'campaigns' %>">
    <%= link_to "Campaigns", admin_campaigns_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="<%= 'active' if active == 'payments' %>">
    <%= link_to "Payment Settings", admin_processor_setup_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="<%= 'active' if active == 'notifications' %>">
    <%= link_to "Notification Settings", admin_notification_setup_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
</ul>

app/views/admin/admin_bank_setup.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'payments' %>

    <ul class="nav nav-tabs nav-bank-setup">
      <li><a href="<%= admin_processor_setup_path %>">Payment Processor</a></li>
      <li class="active"><a href="<%= admin_bank_setup_path %>">Bank Setup</a></li>
    </ul>

  <div id="admin_bank_setup">

    <div class="main_content">

      <% if @bank['is_default'] %>

      <h4>Your banking information's all set up!</h4>
      <div class="account_numbers">
        <p>Routing Number: ****<%= @bank['bank_code_last_four'] %></p>
        <p>Account Number: ****<%= @bank['account_number_last_four'] %></p>
      </div>
      <div class="more_info">
        <p>Campaign funds are transferred automatically to your account within 2 business days of campaign expiration. </p>
        <p>Need to change your bank account? <a href="mailto:team@crowdhoster.com?subject=Please reset my bank account info&body=Hi! I'd like to change my bank account. Please reset it for the Crowdhoster site named:">Send us an email</a>.</p>
      </div>

      <% else %>

      <%= form_tag(admin_bank_setup_path, method: "post", id: "admin_bank_form") %>

      <h4>Personal Information <span class="label show_tooltip" data-placement="right" data-title="BUSINESS ACCOUNTS: <br>To prevent fraud, we verify your personal identity independently of your business bank account. <br> Please enter your personal details here and your business account routing and account numbers in the 'Banking Information' section below.">Business Account?</span></h4>
      <fieldset>

          <div class="form-row clearfix">
            <div class="field">
              <label for="full_legal_name">Legal Name (first and last)</label>
              <input name="full_legal_name" id="full_legal_name" type="text">
            </div>

            <div class="field">
              <label for="phone">Phone (XXX-XXX-XXXX)</label>
              <input name="phone" id="phone" type="text">
            </div>
          </div>

          <div class="form-row clearfix">
            <div class="field">
              <label for="street_address">Street Address</label>
              <input name="street_address" id="street_address" type="text" style="width: 320px">
            </div>

            <div class="field">
              <label for="zip">Zip Code</label>
              <input name="zip" id="zip" type="text" style="width: 100px">
            </div>
          </div>

          <div class="form-row clearfix">
            <div class="field">
            <label>Birth Month</label>
              <select id="birth_month" style="width: 110px">
                  <option value="01" selected>January</option>
                  <option value="02">February</option>
                  <option value="03">March</option>
                  <option value="04">April</option>
                  <option value="05">May</option>
                  <option value="06">June</option>
                  <option value="07">July</option>
                  <option value="08">August</option>
                  <option value="09">September</option>
                  <option value="10">October</option>
                  <option value="11">November</option>
                  <option value="12">December</option>
              </select>
            </div>

            <div class="field">
              <label for="birth_year">Birth Year (YYYY)</label>
              <input name="birth_year" id="birth_year" type="text" style="width: 100px">
            </div>
          </div>

        </fieldset>

        <h4>Banking Information</h4>
        <fieldset>
          <div class="form-row clearfix">
            <div class="field">
              <label for="routing_number">Routing Number <i class="icon icon-info-sign show_tooltip" data-placement="right" data-title="Your routing number is the nine digit number in the bottom left corner of your check."></i></label>
              <input name="bank_routing_number" id="bank_routing_number" type="text">
            </div>

            <div class="field">
              <label for="account_number">Account Number <i class="icon icon-info-sign show_tooltip" data-placement="right" data-title="Your account number is the number to the right of the routing number on your check."></i></label>
              <input name="account_number" id="account_number" type="text">
            </div>
          </div>
        </fieldset>

        <input id="ct_user_id" type="hidden"  name="ct_user_id" value="<%= @ct_admin_id %>" >

        <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
        <span class="loader" data-loader="bank_form" style="display:none"></span>
      </form>
      <div id="errors"></div>

      <% end %>

    </div>

    <div class="settlements">

    </div>

  </div>
  </div>
</div>

<%= javascript_include_tag "https://api.crowdtilt.com/v1/js/crowdtilt.js" %>
<%= javascript_tag do %>
  crowdtilt.init('<%= Rails.env.production? ? 'production' : 'sandbox' %>')
<% end %>

app/views/admin/admin_notification_setup.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'notifications' %>

  <div id="admin_processor_setup">

    <div class="main_content">

      <%= form_for(current_user, url: admin_notification_setup_path, html: {method: "put", id: "admin_notification_form"}) do |f| %>

        <fieldset>
          <legend>Admin notifications</legend>

            <div class="form-row clearfix">
              <div class="field">
                <label for="user_wants_admin_payment_notification" class="checkbox">
                  <%= f.check_box 'wants_admin_payment_notification' %>
                  Notify me via email when someone makes a contribution to my campaign
                </label>
              </div>
            </div>

        </fieldset>

        <br />

        <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
        <span class="loader" data-loader="bank_form" style="display:none"></span>

      <% end %>

    </div>

  </div>
  </div>
</div>

app/views/admin/admin_processor_setup.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'payments' %>

    <ul class="nav nav-tabs nav-processor-setup">
      <li class="active"><a href="<%= admin_processor_setup_path %>">Payment Processor</a></li>
      <li><a href="<%= admin_bank_setup_path %>">Bank Setup</a></li>
    </ul>

  <div id="admin_processor_setup">

    <div class="main_content">

      <% if @settings.payments_activated? %>

      <h4>Your payment processor is all set up!</h4>
      <p>Payments can now be activated for your campaigns.  Please make sure to set up your bank account information by clicking the tab above so that you may receive payouts!</p>

      <% else %>

      <%= form_tag(admin_processor_setup_path, method: "post", id: "admin_crowdtilt_form") %>

      <fieldset>
        <p>Crowdhoster is set up to use the Crowdtilt API for credit card transactions and bank payouts.  Please contact support.api@crowdtilt.com to request production Crowdtilt API credentials.</p>

          <div class="form-row clearfix">
            <div class="field">
              <label for="ct_prod_api_key">Crowdtilt Production API Key</label>
              <input name="ct_prod_api_key" id="ct_prod_api_key" type="text" style="width: 320px">
            </div>
          </div>
          <div class="form-row clearfix">
            <div class="field">
              <label for="ct_prod_api_secret">Crowdtilt Production API Secret</label>
              <input name="ct_prod_api_secret" id="ct_prod_api_secret" type="text" style="width: 320px">
            </div>
          </div>

        </fieldset>

        <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
        <span class="loader" data-loader="bank_form" style="display:none"></span>
      </form>
      <div id="errors"></div>

      <% end %>

    </div>

  </div>
  </div>
</div>

app/views/admin/admin_website.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'website' %>

  <div id="admin_website">

    <%= form_for(@settings, url: admin_website_path, multipart: true, html: { id: "admin_website_form" }) do |f| %>

      <fieldset>
      <legend>Basic Information</legend>

        <div class="field clearfix">
          <p class="explanation">This will be used as the page title (for SEO) and the name in the header. Your site name is also what contributors will see on their credit card statements.</p>
          <label>Site Name</label>
            <%= f.text_field :site_name %>
        </div>

        <div class="field clearfix">
          <p class="explanation">Enter an email address where contributors can reach you.</p>
          <label>Reply To Email</label>
          <%= f.text_field :reply_to_email %>
        </div>

        <div class="field clearfix">
          <p class="explanation">If you would like to display a logo instead of your site name in the header, upload it here. Resize the image before uploading for best results in your template.</p>
          <label>Logo</label>
          <% if @settings.logo_image.file? %>
            <%= image_tag @settings.logo_image.url(:thumb) %><br/>
            <%= f.file_field :logo_image %><br/>
            <%= f.check_box :logo_image_delete %><span>Delete current image</span>
          <% else %>
            <%= f.file_field :logo_image %>
          <% end  %>
        </div>

        <div class="field clearfix">
          <p class="explanation">This will place a link in the header to your blog or other such website where you can provide updates. For example, "Updates" could link to "http://myblog.com"</p>
          <label>Header Link</label>
          <label>Link Text</label>
          <%= f.text_field :header_link_text %>
          <label>URL</label>
          <%= f.text_field :header_link_url %>
        </div>

      <div class="field clearfix">
        <label>Homepage Content</label>
        <p class="explanation inline">This content is shown on the homepage in addition to the campaign titles.</p>
        <%= f.cktext_area :homepage_content %>
      </div>

      </fieldset>

      <fieldset>
      <legend>Sharing Details</legend>

        <div class="field clearfix">
          <p class="explanation">This is the default text that will be used for the tweet button.</p>
          <label>Tweet Text</label>
          <%= f.text_area :tweet_text, rows: 2 %>
        </div>

        <div class="field clearfix">
          <p class="explanation">Include your Facebook app ID here to set up your social sharing buttons. Visit https://developers.facebook.com/apps to create an app for your site. The like button will NOT show up unless you provide this ID.</p>
          <label>Facebook App ID</label>
          <%= f.text_field :facebook_app_id %>
        </div>

        <div class="field clearfix">
          <p class="explanation">The title shown when your site is shared via Facebook. Leave this blank if you want to use your project name.</p>
          <label>Facebook Title</label>
          <%= f.text_field :facebook_title %>
        </div>

        <div class="field clearfix">
          <p class="explanation">The description shown when your site is shared via Facebook.</p>
          <label>Facebook Description</label>
          <%= f.text_area :facebook_description, rows: 2 %>
        </div>

        <div class="field clearfix">
          <p class="explanation">The image shown when your site is shared via facebook. This should have a square aspect ratio and be at least 200px by 200px.</p>
          <label>Facebook Image</label>
          <% if @settings.facebook_image.file? %>
            <%= image_tag @settings.facebook_image.url(:thumb) %><br/>
            <%= f.file_field :facebook_image %><br/>
            <%= f.check_box :facebook_image_delete %><span>Delete current image</span>
          <% else %>
            <%= f.file_field :facebook_image %>
          <% end  %>
        </div>

      </fieldset>

      <fieldset>
      <legend>Google Analytics</legend>

        <div class="field clearfix">
          <p class="explanation">If would like to add tracking to your site, sign up for an account at https://google.com/analytics, then paste your tracking ID here.</p>
          <label>Google Analytics ID</label>
          <%= f.text_field :google_id %>
        </div>

      </fieldset>

      <fieldset>
      <legend>Footer Content</legend>

        <div class="field clearfix">
          <p class="explanation">The text shown in the footer beside the copyright symbol.</p>
          <label>Copyright Text</label>
          <%= f.text_field :copyright_text %>
        </div>

      </fieldset>


      <fieldset>
      <legend><a class="advanced_toggle" href="#">Advanced Settings (click to expand)</a></legend>
        <div id="advanced" style="display:none">

          <div class="field clearfix">
            <p class="explanation">Uncheck this box if you would like all campaigns to be private and not appear on search engines like Google.</p>
            <label>Allow search engines to index your Crowdhoster site</label>
            <%= f.check_box :indexable %>
          </div>
          <div class="field clearfix">
            <p class="explanation">Add your own CSS styles to fully customize the look and feel of your site.</p>
            <label>Custom CSS</label>
            <%= f.text_area :custom_css, rows: 3, style: "width:400px; height: 200px" %>
          </div>

          <div class="field clearfix">
            <p class="explanation">Add your own JavaScript here. Use this field to paste in scripts for analytics tracking, retargeting, etc.</p>
            <label>Custom JavaScript</label>
            <%= f.text_area :custom_js, rows: 3, style: "width:400px; height: 200px" %>
          </div>

       </div>
      </fieldset>


      <%= f.submit "Save", :'class' => "btn btn-primary show_loader", :'data-loader' => "project_form" %>
      <span class="loader" data-loader="project_form" style="display:none"></span>
    <% end %>
  </div>
  </div>
</div>